name: blocks
version: '${project.version}'
author: btarg
main: io.github.btarg.PluginMain
api-version: '1.20'

commands:
  givecustom:
    description: Give a custom block or item
    usage: /givecustom <player> <custom block or item id>
    permission: blocks.givecustomblock

  reloadcustom:
    description: Reload and re-register custom items
    usage: /reloadcustom [blocks | items]
    permission: blocks.reload

  dblist:
    description: List blocks in the custom block database
    usage: /dblist <world>
    permission: blocks.dblist