name: CustomContent
version: '${project.version}'
author: btarg
main: io.github.btarg.PluginMain
api-version: '1.20'
description: The ultimate custom content plugin for Spigot and Paper servers.

commands:
  customcontent:
    aliases:
      - cc
    description: Give a custom block or item, reload custom blocks and items or list custom blocks currently in the world
    usage: /cc [give | reload | listblocks]
    permission: blocks.commands
