name: Origami
version: '${project.version}'
author: btarg
main: io.github.btarg.PluginMain
api-version: '1.20'
description: The ultimate custom content plugin for Spigot and Paper servers.

commands:
  origami:
    aliases:
      - oc
    description: Give a custom block or item, reload custom blocks and items or list custom blocks currently in the world
    usage: /oc [give | reload | listblocks]
    permission: origami.commands
