name: Origami
version: '${version}'
author: btarg
main: io.github.btarg.OrigamiMain
api-version: '1.20'
description: The ultimate custom content plugin for Paper servers.

commands:
  origami:
    aliases:
      - oc
      - cc
    description: Give a custom block or item, reload custom blocks and items, reload the resource pack, or list custom blocks currently placed.
    usage: /oc [give | reload | listblocks]
    permission: origami.commands

permissions:
  origami.commands:
    description: "Use Origami commands"
    default: op
    children:
      permission.node.child: true