name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Execute Gradle build
        run: chmod +x ./gradlew && ./gradlew assemble

      - name: Find Artifact
        run: |
          # Use find command to locate files matching the specified regex
          find build -type f -name 'Origami*.jar' ! -name '*-dev*' -exec echo "Uploading {}" \; -exec mv {} /tmp/artifact \;
      - name: Upload Artifact
        # Upload the files matching the regex as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: Origami-Artifact
          path: /tmp/artifact/Origami*.jar
